### ISSUE TITLE
USAToday grid and clues not formatted correctly

### ISSUE THREAD

**Issue by saulpw** [century-arcade/xd#4]
For example, in this latest xd
 [usatoday-2016-02-13.txt](https://github.com/century-arcade/xd/files/129571/usatoday-2016-02-13.txt):

1) the grid blocks are "-" but should be "#"
2) There are %27 and %22 that should clearly be single and double quotes.

**Comment by vdraceil** [comment]
Done.
Fix available in 'development' branch - https://github.com/century-arcade/xd/commit/f45c36eb755fb56483fd7960e053fd2deb4b0083

**Comment by vdraceil** [comment]
#5
