### ISSUE TITLE
i18n: Please accept '■' (U+25A0) as a block symbol

### ISSUE THREAD

**Issue by katahiromz** [century-arcade/xd#56]
Hello, I'm a Japanese programmer, Katayama Hirofumi MZ.
The Asian people uses their double-width characters (Kanji, Hiragana, and Katakana, etc.).
For example: `あいうえおアイウエオ漢字亜井宇`.

'#' (`U+0023`) is a single-width character, so the appearance of the file contents is ugly.
I propose that your program shalt accept '■' (`U+25A0`) as a block symbol for internationalization.
`U+25A0` is a double-width character for Asian. Thank you!

**Comment by katahiromz** [comment]
Ugly:
![ugly](https://user-images.githubusercontent.com/2107452/143728627-38552096-9257-4499-8761-dfe92f5e83aa.png)

Good:
![good](https://user-images.githubusercontent.com/2107452/143728628-3e2891e0-a2f7-4f04-b578-09f72c9879a1.png)

**Comment by katahiromz** [comment]
See also: https://en.m.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by saulpw** [comment]
Hi @katahiromz, this makes sense to me.  I did not know there are Japanese crossword puzzles.  Do they usually use Kanji, Hiragana, or Katakana?  Can you share an example?

Also, are you using the xd format and library yourself?  It should be pretty easy to make the library accept this character.  I will gladly review a PR if you submit one.

**Comment by katahiromz** [comment]
> Do they usually use Kanji, Hiragana, or Katakana?
The Japanese crossword usually uses Katakana (カタカナ) and Kanji (漢字).

https://www.google.co.jp/search?q=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A+%E3%82%AF%E3%83%AD%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89+%E7%AD%94%E3%81%88&tbm=isch&ved=2ahUKEwiMy82Kvrr0AhXERd4KHewwBBAQ2-cCegQIABAA&oq=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A+%E3%82%AF%E3%83%AD%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89+%E7%AD%94%E3%81%88&gs_lcp=CgNpbWcQA1DrAliMDmCWEGgAcAB4AIABAIgBAJIBAJgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=ECmjYYyDDMSL-Qbs4ZCAAQ&bih=625&biw=1366&hl=ja

> are you using the xd format and library yourself?
I'm creating my crossword generation program, named XWordGiver.

katahiromz/XWordGiver
https://github.com/katahiromz/XWordGiver

![image](https://user-images.githubusercontent.com/2107452/143732993-a611a394-a6cc-43f7-9249-92d769aa15fc.png)

OK, I will create a PR.

**Comment by katahiromz** [comment]
Fixed. Thanks.
